### ISSUE TITLE
Multiple fiilter in StreamTable

### ISSUE THREAD

**Issue by paghdalyogesh** [jiren/StreamTable.js#16]
Hi Jiren,

   I am happy with your code. but i am fetching one problem, can you help me.

 Can you explain me how to implement of multi filter in search_box using different id to call. 

  st = StreamTable('#stream_table',
    {
      view: view, 
      per_page: 10, 
      data_url: 'data/movies.json',
      stream_after: 0.5,
      auto_sorting: true,
      fetch_data_limit: 100,
      callbacks: callbacks,
      pagination: {span: 5, next_text: 'Next &rarr;', prev_text: '&larr; Previous'},
      search_box: '#st_actor', 
	      fields: ['actor'], 
      search_box: '#st_search', 
	      fields: ['year', 'name']
  }
  , data);
});

**Comment by jiren** [comment]
Right now functionality to handle multiple filter is not available. 

You mentions following code. This will search into only two fields year and name.
```javascript
fields: ['year', 'name']
```

**Comment by paghdalyogesh** [comment]
Can you explain me How to implement of functionality of multi filter.
