### ISSUE TITLE
Multi filter query

### ISSUE THREAD

**Issue by Yogeshpatel2014** [jiren/StreamTable.js#17]
Can you explain me how to implement of multi filter, 
 
As you mention of single filter, but we required multi filter base on category, price, rating, and extra text box to find. 
var options = {
	view: view,                  
	data_url: 'data/data.json',
	stream_after: 1,   
	auto_sorting: true,  //Default is false
	fetch_data_limit: 500, 
	pagination:{
		span: 5,                              
		next_text: 'Next &rarr;',              
		prev_text: '&larr; Previous',
		container_class: '.users-pagination', 
		ul_class: '.larger-pagination',       
		per_page_select: true,                 
		per_page_opts: [10,25,50],            
		per_page_class: '.select-box',       
		per_page: 20      
	},
	search_box: '#my-searchbox',
	fields: ['id', 'name']    //Or [1,2] index of array.
}

**Comment by jiren** [comment]
You can use [filter.js](http://github.com/jiren/filter.js) for multiple filter criteria.

**Comment by Yogeshpatel2014** [comment]
But pagination not available in filter.js
