### ISSUE TITLE
Mustache.compile is not a function (from README)

### ISSUE THREAD

**Issue by jeremywadsack** [jiren/StreamTable.js#20]
In the README is says:

```javascript
var template = Mustache.compile($.trim($("#template").html()));

var view = function(record, index){
  return template({record: record, index: index});
};
```

However, the method on current Mustache is [parse](https://github.com/janl/mustache.js#include-templates). There are other changes to how Mustache works too:

```javascript
var template = $.trim($("#template").html());
Mustache.parse(template);

var view = function(record, index){
  return Mustache.render(template, {record: record, index: index});
};
```

Since Mustache.js [0.8.0 / 2 Dec 2013](https://github.com/janl/mustache.js/blob/master/CHANGELOG.md#080--2-dec-2013)

**Comment by jiren** [comment]
Thanks @jeremywadsack . Updated README.
