### ISSUE TITLE
Search is not working if data is adding manually in StreamTable

### ISSUE THREAD

**Issue by vaibhav8186** [jiren/StreamTable.js#37]
When data is filled in first request stream-table search is working but after adding data manually in the stream -table search is not working.

**Comment by jiren** [comment]
Let me know how are you adding data manually? If code snippet available add into comment.

**Comment by vaibhav8186** [comment]
if($('#user_stream_table').length)
      $("#user_stream_table").stream_table(options, data) if typeof data isnt "undefined"

    $('#show').click ->
      if $(this).text() == 'Show Approved'
        $(this).text('Show All')
        $('tr[hide]').removeAttr('hidden')
        $('#user_note_text').text('Showing approved users only.')
        st = $("#user_stream_table").data('st')
        st.data = []
        st.addData(approved)
      else
        $(this).text('Show Approved')
        $('tr[hide]').attr('hidden', 'true')
        $('#user_note_text').text('Showing all users.')
        st = $("#user_stream_table").data('st')
        st.data = []
        st.addData(data)

**Comment by vaibhav8186** [comment]
After data adding manually if I search for something then  
 view = (record, index) ->
    if record.employee_detail
      record.id = record.employee_detail.employee_id
this code is not getting record. That's why search is not working ....

**Comment by jiren** [comment]
when adding data stream table creating search index so when you clear data search index needs to be clear. So call`st.clearAndBuildTextIndex()` after calling `st.addData`.
